name: Update Datetime File

on:
  push:
    branches:
      - abhishek_GithubAction2

jobs:
  update-datetime:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python (optional, only if needed for your setup)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
          brew install pkg-config libsodium openssl zeromq just jq

      - name: Set up Rust
        run: |
          rustc --version
          rustup default 1.78.0
          rustc --version

      - name: Run the script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
        run: |
          #COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          #if [[ "$COMMIT_MESSAGE" == *"RunAction"* ]]; then
            echo "Commit message contains 'RunAction'."
            chmod +x ./aries/wrappers/uniffi-aries-vcx/scripts/ios.build.cargo.sh
            ./aries/wrappers/uniffi-aries-vcx/scripts/ios.build.cargo.sh
            chmod +x ./create_datetime_file.sh
            ./create_datetime_file.sh
          #else
            #echo "Commit message does not contain 'RunAction'."
            #exit 0
          #fi

          #git config --global user.name "abhishek"
          #git config --global user.email "abhishek@instnt.org"

          #git add -A
          #git commit -m "Update datetime.txt with current date and time"
          #git push
